"""项目配置占位，后续可以把股票池、风险参数等集中放在这里。"""

# M1 阶段使用固定股票池，优先选择流动性较好的美股 ticker。
DEFAULT_STOCK_UNIVERSE = [
    "AAPL", "MSFT", "NVDA", "TSLA", "AMD", "MU", "META", "GOOGL", "AMZN", "NFLX",
    "AVGO", "SMCI", "INTC", "QCOM", "ARM", "PLTR", "COIN", "MSTR", "MARA", "RIOT",
    "SOFI", "RIVN", "LCID", "NIO", "BABA", "PDD", "JD", "UBER", "SHOP", "SNOW",
    "CRWD", "PANW", "TSM", "BA", "JPM", "BAC", "XOM", "CVX", "SPY", "QQQ",
]

# 策略回测股票池：以标普500 + 纳斯达克100常见成分股为基础手工整理。
# 这里排除了常见中概股/中资ADR，市值过滤会在回测时用 yfinance 当前 market cap 再近似筛选。
BACKTEST_STOCK_UNIVERSE = """
AAPL MSFT NVDA AMZN META GOOGL GOOG AVGO TSLA COST NFLX AMD ADBE PEP CSCO TMUS INTU QCOM TXN AMAT
AMGN HON ISRG BKNG SBUX ADP GILD VRTX MU LRCX PANW ADI KLAC MELI CRWD REGN PYPL MAR CDNS SNPS
ORLY CSX CEG ABNB MRVL FTNT WDAY NXPI ROP PCAR CHTR MNST PAYX AEP KDP ROST FAST ODFL EXC IDXX
CTAS EA XEL VRSK DDOG TEAM TTD ZS MDB DXCM GEHC ON BIIB ILMN WBD LCID RIVN MRNA SIRI DLTR
BRK-B LLY JPM V UNH XOM MA JNJ PG HD ABBV BAC KO CVX WMT MRK CRM ORCL WFC ACN
MCD LIN TMO ABT DHR DIS PM IBM NOW CAT GE VZ GS RTX AXP ISRG NEE MS PFE UBER
SPGI LOW QCOM BKNG UNP TJX BLK T HON PGR SYK ETN BSX VRTX C SCHW LMT CB ADP MDT
MMC COP PLD AMT AMGN DE ADI ELV PANW GILD SBUX BMY FI SO CI MU MDLZ ANET ICE MO
DUK SHW WM KLAC INTC MCO ZTS APH CME CL HCA EQIX CDNS SNPS NKE UPS PH TDG CMG MSI
PYPL USB EOG PNC REGN AON ORLY ITW MCK MMM APD EMR GD FDX MAR BDX TGT ECL CSX NOC
FCX NSC CARR AJG ROP TFC SLB NXPI ADSK AFL PSX GM HWM MET AZO TRV HLT PCAR O COF
ROST MPC SRE AEP SPG OKE URI FTNT DHI KMB DLR PSA ALL AMP GWW PAYX FICO CPRT LEN VLO
LHX AIG KMI CCI MSCI F IQV CHTR TEL BK COR PRU CMI KVUE RSG D FIS PEG PCG AME
EA FAST EXC KR CTVA VRSK YUM CTAS HES OTIS VMC IR ODFL GEV IT EW GIS SYY NUE ACGL
MLM VICI LVS EXR BKR KDP RCL WAB IDXX DD ED XYL HIG IRM EFX HUM DFS MTD AVB EIX
HPQ EL WTW CBRE DXCM TSCO BRO WEC CSGP ROK LYB PPG ANSS ON ADM FITB EQR GPN CDW CAH
KEYS TTWO KHC FTV NVR DVN DOW CHD DOV HAL PHM AWK TROW WST NTAP BR BIIB TYL DECK SBAC
VLTO STT WY MTB HPE LYV FE PPL ROL STX IFF STE WDC ES ZBH EQT AEE INVH TER LDOS
PTC WRB CBOE WAT HBAN RF CINF ATO CMS COO TDY MKC MOH BALL SYF GDDY CFG TSN PODD CLX
DRI BBY ULTA OMC EXPE HOLX ARE LH PKG LUV MAA J ZBRA VTR FSLR NRG ESS NTRS DG IEX
MAS TRGP L STLD EXPD AVY TXT DGX CF ALGN K GEN SWKS PNR MRO VRSN EG NDSN KEY DOC
AKAM RVTY SNA DPZ LNT AMCR SWK UDR CAG POOL JBHT EVRG NI UHS JNPR REG KIM EPAM CPT HST
IPG AOS LKQ CHRW EMN ALLE BG TFX TECH BXP INCY JKHY QRVO FFIV CTRA TAP RL WRK TPR GNRC
PAYC HSIC MTCH NWSA GL WYNN AAL APA MKTX PNW FOXA FOX MOS CZR BWA HAS FRT MGM IVZ PARA
ENPH ETSY NCLH DAY SOLV SW CPAY AIZ BEN CRL DVA ERIE FDS HII HRL LW MHK RJF SMCI TRMB
UHS WBA WMT APO KKR COIN PLTR SNOW NET OKTA U AFRM HOOD SOFI MSTR MARA RIOT CELH CAVA DELL
""".split()
