"""Real-input adapter for fixed B1.1 engineering samples, not a stitched portfolio.

All signals/orders/fills are generated by ReplayEngine. This module only pins
source objects, supplies the event clock, and stops an engineering sample once
its natural campaign (if any) has actually settled. No synthetic data fallback.
"""
from __future__ import annotations
import argparse
from dataclasses import asdict
import hashlib
import json
from pathlib import Path
import pandas as pd
import pandas_market_calendars as mcal
from .b11_runtime import ROOT, PREVIOUS, REPO, utc, sha, read, write, status
from .replay import ReplayEngine, ReplayConfig, calendar_events, PRIORITY

NY='America/New_York'
DATA=ROOT/'data'


def digest(value):
    return hashlib.sha256(json.dumps(value,sort_keys=True,default=str).encode()).hexdigest()


def clean(value):
    if isinstance(value,dict):return {str(k):clean(v) for k,v in value.items()}
    if isinstance(value,(list,tuple)):return [clean(v) for v in value]
    if hasattr(value,'item'):return clean(value.item())
    if isinstance(value,float) and pd.isna(value):return None
    if isinstance(value,pd.Timestamp):return value.isoformat()
    return value


def event(kind,symbol,at,payload,identity=None):
    return {'event_id':identity or digest([kind,symbol,str(at),payload]),'kind':kind,
            'at':pd.Timestamp(at).isoformat(),'symbol':symbol,'payload':clean(payload)}


class Inputs:
    def __init__(self):
        self.schedule=mcal.get_calendar('NYSE').schedule('2025-01-01','2026-10-31')
        self.clocks={str(d.date()):r for d,r in self.schedule.iterrows()}
        self.first=clean(pd.read_csv(DATA/'FIRST20_FROZEN.csv').to_dict('records'))
        self.samples=read(DATA/'FIRST20_INPUTS.json')
        self.histories={r['symbol']:r for r in read(DATA/'HISTORY_INPUTS.json')}
        self.earnings=read(ROOT/'earnings/PRIMARY_EARNINGS.json')
        self.actions=read(DATA/'corporate_actions.json')
        self.pinned={}
        self.cache={}
        for p in [DATA/'FIRST20_FROZEN.csv',DATA/'FIRST20_INPUTS.json',DATA/'HISTORY_INPUTS.json',
                  DATA/'corporate_actions.json',ROOT/'earnings/PRIMARY_EARNINGS.json',ROOT/'B11_PROTOCOL.json']:
            self.pinned[str(p)]=sha(p)

    def frame(self,path):
        p=Path(path)
        self.pinned[str(p)]=sha(p)
        return pd.read_parquet(p)

    def symbol_data(self,symbol):
        if symbol in self.cache:return self.cache[symbol]
        if symbol not in self.histories:
            return pd.DataFrame(),pd.DataFrame(),{}
        h=self.histories[symbol]
        daily=self.frame(h['rth']['path']).set_index('trade_date',drop=False)
        ranking=DATA/'RANKING_VOLUME_PRIOR20.csv'
        if ranking.exists():
            self.pinned[str(ranking)]=sha(ranking)
            rankrows=pd.read_csv(ranking)
            for r in rankrows[rankrows.symbol.eq(symbol)].to_dict('records'):
                if r['trade_date'] in daily.index:
                    daily.loc[r['trade_date'],'volume']=r['rth_plus_observed_auction_volume']
                    daily.loc[r['trade_date'],'ranking_volume_basis']=r['ranking_volume_status']
        minute=self.frame(h['minutes']['path'])
        minute['time']=pd.to_datetime(minute.timestamp,utc=True)
        minute['ny_day']=minute.time.dt.tz_convert(NY).dt.strftime('%Y-%m-%d')
        quotes={}
        refs=[w['receipt'] for s in self.samples if s['symbol']==symbol for w in s['quote_windows']]
        supplemental=DATA/'EXIT_QUOTE_INPUTS.json'
        if supplemental.exists():
            self.pinned[str(supplemental)]=sha(supplemental)
            refs += [x['receipt'] for x in read(supplemental) if x['symbol']==symbol]
        for ref in refs:
            p=Path(ref['path'])/'data.parquet'
            if not ref.get('complete') or not p.exists():continue
            for q in self.frame(p).to_dict('records'):
                t=pd.Timestamp(q['t']); day=str(t.tz_convert(NY).date())
                payload={'bid':float(q['bp']),'ask':float(q['ap']),
                         'bid_size':float(q['bs']),'ask_size':float(q['as']),
                         'bid_exchange':q.get('bx'),'ask_exchange':q.get('ax'),
                         'conditions':list(q.get('c',[])), 'timestamp':t.isoformat(),
                         'size_unit':q.get('size_unit','UNKNOWN'),'available_at':t.isoformat(),
                         'source_received_at':q.get('source_received_at',ref.get('last_source_received_at','UNKNOWN')),
                         'historical_network_received_at':'UNKNOWN','availability_basis':'HISTORICAL_EVENT_CLOCK_NOT_LIVE_BASIC_RECEIPT'}
                qid=q.get('quote_id') or digest({k:v for k,v in payload.items() if k!='source_received_at'})
                # Identical vendor records retrieved by overlapping requests have
                # one inventory identity; all source files remain in the manifest.
                quotes.setdefault(day,{})[qid]=event('QUOTE',symbol,t,payload,'quote:'+qid)
        self.cache[symbol]=(daily,minute,{d:list(v.values()) for d,v in quotes.items()})
        return self.cache[symbol]

    def daily_event(self,symbol,row):
        day=row['trade_date']; close=self.clocks[day].market_close
        at=close+pd.Timedelta(minutes=1)
        payload={k:row.get(k) for k in ['open','high','low','close','volume','regular_session_verified','action_units_verified','source_received_at']}
        payload.update(session_date=day,available_at=at.isoformat(),historical_network_received_at='UNKNOWN',
                       data_basis='VENDOR_STANDARD_FIELDS',
                       availability_basis='FINAL_HISTORICAL_RTH_SNAPSHOT_ASSUMED_AVAILABLE_AT_CLOSE_PLUS1_MINUTE; NOT_VINTAGE_OR_BASIC_LIVE_PROOF',
                       price_basis='RTH_MINUTES_PLUS_VENDOR_OFFICIAL_CLOSE',
                       volume_basis=row.get('ranking_volume_basis','RTH_MINUTE_VOLUME_WITHOUT_CLOSING_AUCTION'),
                       independent_point_audit='NOT_INDEPENDENTLY_CHECKED_EACH_POINT')
        return event('DAILY_BAR',symbol,at,payload,'daily:'+symbol+':'+day)

    def earnings_events(self,symbol,tier,start):
        result=[]
        fact=next((r for r in self.earnings['facts'] if r['symbol']==symbol),{})
        if not fact.get('coverage_complete'):return result
        if tier=='B':
            at=pd.Timestamp(start,tz=NY)
            for label,key,urlkey in [('previous','previous_release_date_ny','previous_source'),('next','next_release_date_ny','next_source')]:
                revision={'event_id':symbol+':'+fact[key],'actual_release_date':fact[key],
                          'source':fact[urlkey],'event_kind':'earnings_release','actual_time_precision':'DATE'}
                result.append(event('EARNINGS_REVISION',symbol,at,{'revision':revision,'coverage_complete':True,
                    'coverage_start':fact['coverage_start'],'coverage_end':fact['coverage_end'],
                    'coverage_source':fact['completeness_basis'],'source_received_at':self.earnings['created_at'],
                    'historical_network_received_at':'UNKNOWN','tier':'RETROSPECTIVE_EARNINGS_EXCLUSION'},'earnings:B:'+symbol+':'+label))
        else:
            for plan in self.earnings['plans']:
                if plan['symbol']!=symbol:continue
                at=pd.Timestamp(plan['conservative_known_at_ny'],tz=NY)
                revision={'event_id':symbol+':'+plan['planned_release_date'],'planned_date':plan['planned_release_date'],
                          'known_at':at.isoformat(),'actual_release_date':fact['next_release_date_ny'],
                          'source':plan['source'],'event_kind':'earnings_release','actual_time_precision':'DATE'}
                result.append(event('EARNINGS_REVISION',symbol,at,{'revision':revision,'coverage_complete':True,
                    'availability_basis':plan['availability_basis'],'source_received_at':self.earnings['created_at'],
                    'historical_network_received_at':'UNKNOWN'},'earnings:A:'+symbol+':'+digest([plan['planned_release_date'],at.isoformat(),plan['source']])))
        return result

    def corporate_events(self,symbol,first,last):
        result=[]
        for x in self.actions.get('corporate_actions',{}).get('cash_dividends',[]):
            if x['symbol']!=symbol:continue
            ex=x['ex_date']; pay=x.get('payable_date')
            if ex<first or ex>last:continue
            at=pd.Timestamp(ex,tz=NY)
            payload={'action_id':x['id'],'amount_per_share':x['rate'],'pay_date':pay or 'UNKNOWN',
                     'source':'Alpaca corporate actions','known_at_historical':'UNKNOWN',
                     'data_basis':'VENDOR_STANDARD_HISTORICAL_ACTIONS'}
            result.append(event('DIVIDEND_EX',symbol,at,payload,'divex:'+x['id']))
            if pay and pay<=last:
                result.append(event('DIVIDEND_PAY',symbol,pd.Timestamp(pay,tz=NY),{'action_id':x['id']},'divpay:'+x['id']))
        # Actual endpoint found no split effective inside sample warmup/replay.
        # Do not silently ignore a new split if the immutable input is revised.
        for kind in ('forward_splits','reverse_splits'):
            for x in self.actions.get('corporate_actions',{}).get(kind,[]):
                if x.get('symbol')==symbol and first<=x.get('ex_date','')<=last:
                    raise ValueError('NEW_SPLIT_INPUT_REQUIRES_EXPLICIT_RATIO_FIELD_REVIEW')
        return result

    def day_events(self,symbol,day,daily,minutes,quotes):
        c=self.clocks.get(day)
        result=[]
        if c is None:return result
        rows=minutes[minutes.ny_day.eq(day)] if len(minutes) else minutes
        if len(rows):rows=rows[(rows.time>=c.market_open)&(rows.time<c.market_close)]
        for r in rows.to_dict('records'):
            end=r['time']+pd.Timedelta(minutes=1)
            result.append(event('MINUTE_BAR',symbol,end,{'bar_end':end.isoformat(),
                **{k:r[k] for k in ['open','high','low','close','volume']},'available_at':end.isoformat(),
                'source_received_at':self.histories[symbol]['minutes']['receipt']['last_source_received_at'],
                'historical_network_received_at':'UNKNOWN','availability_basis':'COMPLETED_MINUTE_EVENT_CLOCK_NOT_ACTUAL_NETWORK_RECEIPT'},
                'minute:'+symbol+':'+str(r['timestamp'])))
        if len(daily) and day in daily.index:result.append(self.daily_event(symbol,daily.loc[day].to_dict()))
        elif day>= '2026-01-02':result.append(event('DATA_GAP',symbol,c.market_close,{'reason':'RTH_DAILY_MISSING','category':'MARKET_DATA'}))
        result.extend(quotes.get(day,[]))
        return result


def run_sample(inputs,rank,tier,version='initial',stop_after_days=None):
    sample=inputs.first[rank-1]; symbol=sample['symbol'];first=sample['trade_date'];last='2026-09-11'
    run_id=f'sample_{rank:02d}_{symbol}_{first}_{tier}_{version}'
    output=ROOT/'replay'/version/f'tier_{tier}'/run_id
    output.mkdir(parents=True,exist_ok=True)
    cfg=ReplayConfig(run_id=run_id,earnings_tier=tier,data_basis='VENDOR_STANDARD_FIELDS',start=first,end=last,
                     checkpoint_every=0,entry_dates=(first,),research_scope='FIXED_FIRST20_ENGINEERING_SAMPLE_NOT_PORTFOLIO')
    scope='KEEP' if sample['scope_policy']=='KEEP' else 'EXCLUDE'
    universe={symbol:{'security_id':sample['local_security_id'],'scope':scope,'identity_sort_hash':sample['identity_sort_hash']}}
    daily,minutes,quotes=inputs.symbol_data(symbol)
    spec={'config':asdict(cfg),'sample':sample,'source_files':dict(inputs.pinned),
          'engine_sha256':sha(REPO/'src/ben_b1/replay.py'),'ledger_sha256':sha(REPO/'src/ben_b1/ledger.py'),
          'adapter_sha256':sha(Path(__file__))}
    spec_path=output/'RUN_SPEC.json'
    if spec_path.exists():
        old=read(spec_path)
        if any(sha(p)!=h for p,h in old['source_files'].items()) or any(old[k]!=spec[k] for k in ['engine_sha256','ledger_sha256','adapter_sha256']):
            raise ValueError('IMMUTABLE_RUN_SOURCE_CHANGED_USE_NEW_VERSION')
    else:write(spec_path,spec)
    if (output/'summary.json').exists():return read(output/'summary.json')
    checkpoint=output/'checkpoint.json'
    engine=ReplayEngine.restore(checkpoint,inputs.schedule) if checkpoint.exists() else ReplayEngine(inputs.schedule,cfg,universe,checkpoint)
    warmup=[inputs.daily_event(symbol,row) for row in daily[daily.trade_date<first].to_dict('records')] if len(daily) else []
    extras=inputs.earnings_events(symbol,tier,first)+inputs.corporate_events(symbol,first,last)
    start_at=pd.Timestamp(first,tz=NY)
    engine.run(warmup+[e for e in extras if pd.Timestamp(e['at'])<start_at])
    extras_by_day={}
    for item in extras:extras_by_day.setdefault(str(pd.Timestamp(item['at']).tz_convert(NY).date()),[]).append(item)
    stop_reason='FIXED_END_WITH_RETAINED_STATE'
    resume_day=max(first,str(pd.Timestamp(engine.state['at']).tz_convert(NY).date())) if engine.state['at'] else first
    for index,date in enumerate(pd.date_range(resume_day,last)):
        day=str(date.date())
        events=calendar_events(inputs.schedule,day,day)+extras_by_day.get(day,[])
        events += inputs.day_events(symbol,day,daily,minutes,quotes)
        engine.run(events)
        write(output/'progress.json',{'at':utc(),'sample':rank,'tier':tier,'processed_day':day,
                                     'events':engine.state['events_processed'],'buys':len([f for f in engine.ledger.fills.values() if f['side']=='BUY']),
                                     'open_positions':list(engine.ledger.positions)})
        unpaid_dividends=any(r['status']!='PAID' and r['amount']>0 for r in engine.ledger.dividend_receivables.values())
        if not engine.ledger.positions and not engine.ledger.settlements and not unpaid_dividends and not any(o['status']=='OPEN' for o in engine.orders.values()):
            stop_reason='NATURAL_CAMPAIGN_SETTLED' if engine.ledger.fills else 'ENTRY_DAY_EXPIRED_WITHOUT_NATURAL_FILL'
            break
        if stop_after_days and index+1>=stop_after_days:
            stop_reason='EXPLICIT_DIAGNOSTIC_CHECKPOINT_PENDING_INPUT_ENRICHMENT';break
    engine.export(output)
    summary=engine.summary()
    summary.update(sample_rank=rank,symbol=symbol,sample_date=first,processed_through=day,
                   stop_reason=stop_reason,output=str(output),source_scope_policy=sample['scope_policy'],
                   full_pool_account=False,not_strategy_performance_validation=True,
                   earnings_source_version=self_hash(inputs.earnings),source_files=inputs.pinned)
    write(output/'summary.json',summary)
    # Real input/event evidence is reproducible from pinned files. A checkpoint
    # copied/restored into this isolated run is replayed once more with the last
    # exact batch; every event must be skipped with identical state and fees.
    restored=ReplayEngine.restore(output/'checkpoint.json',inputs.schedule)
    before=digest(restored.to_dict())
    restored.run(events)
    after=digest(restored.to_dict())
    write(output/'RECOVERY_IDEMPOTENCY.json',{'tested_at':utc(),'before':before,'after':after,
        'same_state':before==after,'last_batch_events_replayed':len(events),'status':'PASS' if before==after else 'FAIL',
        'synthetic':False,'original_data_unchanged':True})
    print(json.dumps({k:summary.get(k) for k in ['sample_rank','symbol','sample_date','earnings_tier','status','buy_fills','sell_fills','pending_exit_count','error_count','processed_through']},ensure_ascii=False),flush=True)
    return summary


def self_hash(value):return digest(value)


def run(tier='A',version='initial',ranks=None,stop_after_days=None):
    inputs=Inputs()
    results=[]
    for rank in (ranks or list(range(1,21))):
        status('REAL_ENGINEERING_REPLAY',persistent_research_worker_running=True,actual_runner_pid=__import__('os').getpid(),
               checkpoint=f'replay/{version}/tier_{tier}',current_sample=rank,earnings_tier=tier)
        try:results.append(run_sample(inputs,rank,tier,version,stop_after_days))
        except Exception as exc:
            result={'sample_rank':rank,'status':'REPLAY_ADAPTER_FAILED','reason':str(exc),'exception':type(exc).__name__}
            write(ROOT/'replay'/version/f'tier_{tier}'/f'adapter_error_{rank:02d}.json',
                  {**result,'traceback':__import__('traceback').format_exc(),'recorded_at':utc()})
            results.append(result);print(json.dumps(result),flush=True)
        write(ROOT/'replay'/version/f'tier_{tier}'/'RUN_SUMMARY.json',results)
    write(ROOT/'replay'/version/f'tier_{tier}'/'INPUT_HASHES.json',{'created_at':utc(),'files':inputs.pinned})
    status('REAL_ENGINEERING_REPLAY_BATCH_FINISHED',persistent_research_worker_running=False,current_sample=None)
    return results


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--tier',choices=['A','B'],default='A')
    parser.add_argument('--version',default='initial');parser.add_argument('--ranks',nargs='*',type=int)
    parser.add_argument('--stop-after-days',type=int)
    args=parser.parse_args();run(args.tier,args.version,args.ranks,args.stop_after_days)
